name: ci 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build with cmake
    steps:
    - uses: actions/checkout@v4
    
    - name: install deps
      run: sudo apt install libsdl2-2.0-0 libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

    - name: configure 
      run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build

    - name: build 
      run: cd build; make

  style:
    runs-on: ubuntu-latest
    name: check style 
    strategy:
      matrix:
        path:
          - 'sources'
          - 'include'
          - 'examples'
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '18'
        check-path: ${{ matrix.path }}
        fallback-style: 'Mozilla'
